### ISSUE TITLE
Morning session Code Review.

### ISSUE THREAD

**Issue by Itswali** [fmanimashaun/My-Portfolio#5]
Remove the extra spaces from the code for better readability and clean code.

**Comment by Itswali** [comment]
Nice and meaningful comment on the pull request ,
NIce Job there.

**Comment by alex1779** [comment]
Good description in the pull request.

**Comment by Itswali** [comment]
Nice Job using the meaningful tags in HTML.
Just make the code clean for better readability.
Remove unnecessary spaces and position the lines correctly.

**Comment by npydi** [comment]
> Remove the extra spaces from the code for better readability and clean code.
Looks clean, good job!
